name: CI

permissions:
  contents: read

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2]
        dependencies: [lowest, highest]
        experimental: [false]
    name: 👷 CI PHP-${{ matrix.php }} ${{ matrix.dependencies }} on ${{ matrix.os }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Cache dependencies
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-php-${{ matrix.php }}-composer-

      - name: ⚡️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, gd, intl, mbstring, openssl, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2, php-cs-fixer, phpunit, vimeo/psalm
          coverage: pcov

      - name: 🍱 Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: ✅ Check code lint
        run: composer lint

      - name: ⚗️  Run static analysis
        run: |
          composer verify
          composer analyse
          composer inspect

      - name: 🧪 Run unit tests
        run: composer test

      - name: 🐛 Check all code bugs
        run: composer debug
